language: python
python:
  - 3.5.3
  - 3.6.0

script: echo "Running tests against $(python -v) ..."
script: printenv

jobs:
  include:
    - stage: release
      env:
        - DEPLOYING=true
      python: "3.6.0"
      script: echo "Deploying"
      script: printenv
