dist: trusty
language: python
python:
- 3.5.3
before_script:
- set DEPLOYING=true
script:
- printenv
cache: pip
notifications:
  email: false

jobs:
  include:
    - stage: Deployment
      env:
        - DEPLOYING=true
      script: echo "Deploying to GitHub releases ..."
